import js from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import globals from 'globals';
import { defineConfig } from 'eslint/config';
import eslintConfigPrettier from 'eslint-config-prettier/flat';

export default defineConfig([
	{
		files: ['**/*.{js,mjs,cjs}'],
		plugins: { js, import: importPlugin },
		extends: ['js/recommended'],
		// remove globals.node if project is only in the browser
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node,
			},
		},
		rules: {
			quotes: 2,
			eqeqeq: 2,
			semi: 2,
			radix: 2,
			camelcase: [
				2,
				{
					properties: 'always',
					ignoreDestructuring: true,
					ignoreImports: true,
				},
			],
			'no-redeclare': 2,
			'no-var': 2,
			'prefer-const': 2,
			'no-undef': 2,
			'no-new-object': 2,
			'object-shorthand': 2,
			'quote-props': 2,
			'no-prototype-builtins': 2,
			'prefer-object-spread': 2,
			'no-array-constructor': 2,
			'array-callback-return': 2,
			'prefer-destructuring': 2,
			'prefer-template': 2,
			'template-curly-spacing': 2,
			'no-use-before-define': 2,
			'no-eval': 2,
			'no-useless-escape': 2,
			'func-names': [2, 'as-needed'],
			'wrap-iife': 2,
			'no-loop-func': 2,
			'prefer-rest-params': 2,
			'default-param-last': 2,
			'no-new-func': 2,
			'space-before-blocks': 2,
			'space-before-function-paren': 2,
			'no-param-reassign': 2,
			'prefer-spread': 2,
			'function-paren-newline': [2, 'consistent'],
			'prefer-arrow-callback': 2,
			'arrow-spacing': 2,
			'arrow-parens': 2,
			'arrow-body-style': 2,
			'no-confusing-arrow': 2,
			'implicit-arrow-linebreak': 2,
			'no-useless-constructor': 2,
			'no-dupe-class-members': 2,
			'class-methods-use-this': 2,
			'no-duplicate-imports': 2,
			'object-curly-newline': [
				2,
				{
					ObjectExpression: { multiline: true, minProperties: 2 },
					ImportDeclaration: { multiline: true, minProperties: 2 },
				},
			],
			'import/no-mutable-exports': 2,
			'import/first': 2,
			'import/no-webpack-loader-syntax': 2,
			'no-iterator': 2,
			'generator-star-spacing': 2,
			'dot-notation': 2,
			'no-implicit-globals': 2,
			'one-var': [2, 'never'],
			'no-multi-assign': 2,
			'operator-linebreak': [2, 'none'],
			'no-unused-vars': 2,
			'no-case-declarations': 2,
			'no-nested-ternary': 2,
			'no-unneeded-ternary': 2,
			'no-mixed-operators': 2,
			'nonblock-statement-body-position': 2,
			'brace-style': 2,
			'no-else-return': 2,
			'spaced-comment': 2,
			'keyword-spacing': 2,
			'space-infix-ops': 2,
			'eol-last': 2,
			'no-whitespace-before-property': 2,
			'padded-blocks': 2,
			'no-multiple-empty-lines': 2,
			'no-trailing-spaces': 2,
			'space-in-parens': 2,
			'object-curly-spacing': 2,
			'array-bracket-spacing': 2,
			'block-spacing': 2,
			'comma-spacing': 2,
			'computed-property-spacing': 2,
			'func-call-spacing': 2,
			'key-spacing': 2,
			'comma-style': 2,
			'comma-dangle': [2, 'always-multiline'],
			'no-new-wrappers': 2,
			'new-cap': 2,
			'no-underscore-dangle': 2,
			'no-restricted-globals': 2,
		},
	},
	eslintConfigPrettier,
]);
